In [4]:
import os
os.listdir()

['NoMongoStartingNB.ipynb',
 'Test2.ipynb',
 'Copy of Javed Jutt.xlsx',
 'TestFile1.ipynb',
 '.ipynb_checkpoints']

In [5]:
import pandas

In [10]:
df1 = pandas.read_excel('Copy of Javed Jutt.xlsx', sheet_name=0)

In [8]:
print(df1)

     Code                                  Name  Javed Jutt Balance  \
0   465.0                           A.M Traders             32702.0
1   542.0      Adnan Siddique (Fateh Pur Kamal)             16566.0
2   448.0                      Alamgeer Traders                 0.0
3   558.0                    Al Rayan Marketing             37705.0
4   519.0                           Ali Traders             55560.0
5   449.0                           Ameen Sweet              6934.0
6   180.0                          Arif Traders              5000.0
7   467.0                        Arshad Traders             55626.0
8   439.0                         Asad Brothers             10662.0
9   195.0                       Ashraf Brothers             34026.0
10  268.0                          Atif Traders                 0.0
11  481.0                       Bahadur Traders                 0.0
12  251.0                        Bhatti Traders                 0.0
13  175.0                         Bilal Traders                 0.0
14  552.0                     Chaudhari Traders             35764.0
15  463.0                           Chand Sweet             10704.0
16  551.0                          Eman Traders             27420.0
17  484.0            Fazal Sweet (M.Javed Jutt)             13910.0
18  174.0                           Geo Traders             18672.0
19  545.0                     Hijar And Ghafoor              8805.0
20  493.0                           H.K Traders             17300.0
21  548.0             Jahangir Trd (Bahawalpur)             19027.0
22  488.0                      Jahangir Traders             96015.0
23  482.0                        Kafeel Traders             20375.0
24  528.0                      Khanzada Traders             11854.0
25  543.0                        Kamran Traders             18520.0
26  486.0                       Khowaja Traders             68123.0
27  503.0                         Lodhi Traders             28692.0
28  455.0                           M.A Traders                 0.0
29  181.0                            Malik Amir                 0.0
30  201.0  Mudasir Iqbal Traders (M.Javed Jutt)             18375.0
31  540.0                  Mohsin Confectionery             16680.0
32  464.0                      Mughal Book Depo             57355.0
33  182.0                       Nazeer And Sons                 0.0
34  304.0                         Noman Traders                 0.0
35  254.0                           Pak Tijarah             61373.0
36  483.0                         Rehman Agency              8205.0
37  546.0                           Roshan Guru              3424.0
38  462.0        Shehroz Traders (M.Javed Jutt)            110016.0
39  461.0                         Urooj Traders            127580.0
40  462.0                         Yawar Traders                 NaN
41    NaN              Total Updated 12/12/2015           1052970.0
42    NaN                                   NaN                 NaN
43    NaN                       Unknown Deposit                 NaN
44    NaN           Sales 11th Nov till 3rd Dec                 NaN
45    NaN              Javed Jutt Balance Total                 NaN
46    NaN                            Difference                 NaN
47    NaN                                   NaN                 NaN
48    NaN              Computer Balance 3rd Dec                 NaN

    Payments Recived After 11th Nov  Sales(1st Dec till 12th Dec)  \
0                               NaN                           NaN
1                               NaN                           NaN
2                               NaN                           NaN
3                               NaN                        8855.0
4                               NaN                           NaN
5                               NaN                           NaN
6                               NaN                           NaN
7                               NaN                        8460.0
8                               NaN                           NaN
9                               NaN                           NaN
10                              NaN                           NaN
11                              NaN                           NaN
12                              NaN                           NaN
13                              NaN                           NaN
14                              NaN                           NaN
15                              NaN                           NaN
16                              NaN                           NaN
17                              NaN                           NaN
18                              NaN                        6758.0
19                              NaN                           NaN
20                              NaN                           NaN
21                              NaN                       15488.0
22                              NaN                           NaN
23                              NaN                           NaN
24                              NaN                           NaN
25                              NaN                           NaN
26                              NaN                           NaN
27                              NaN                           NaN
28                              NaN                           NaN
29                              NaN                           NaN
30                              NaN                           NaN
31                              NaN                           NaN
32                              NaN                           NaN
33                              NaN                           NaN
34                              NaN                           NaN
35                              NaN                           NaN
36                              NaN                           NaN
37                              NaN                        5271.0
38                              NaN                           NaN
39                              NaN                           NaN
40                              NaN                           NaN
41                              0.0                       44832.0
42                              NaN                           NaN
43                              NaN                           NaN
44                              NaN                           NaN
45                              NaN                           NaN
46                              NaN                           NaN
47                              NaN                           NaN
48                              NaN                           NaN

    NET Balance  ERP Balance
0       32702.0          NaN
1       16566.0          NaN
2           0.0          NaN
3       46560.0          NaN
4       55560.0          NaN
5        6934.0          NaN
6        5000.0          NaN
7       64086.0          NaN
8       10662.0          NaN
9       34026.0          NaN
10          0.0          NaN
11          0.0          NaN
12          0.0          NaN
13          0.0          NaN
14      35764.0          NaN
15      10704.0          NaN
16      27420.0          NaN
17      13910.0          NaN
18      25430.0          NaN
19       8805.0          NaN
20      17300.0          NaN
21      34515.0          NaN
22      96015.0          NaN
23      20375.0          NaN
24      11854.0          NaN
25      18520.0          NaN
26      68123.0          NaN
27      28692.0          NaN
28          0.0          NaN
29          0.0          NaN
30      18375.0          NaN
31      16680.0          NaN
32      57355.0          NaN
33          0.0          NaN
34          0.0          NaN
35      61373.0          NaN
36       8205.0          NaN
37       8695.0          NaN
38     110016.0          NaN
39     127580.0          NaN
40          0.0          NaN
41    1097802.0          NaN
42          NaN          NaN
43          NaN          NaN
44          NaN          NaN
45          NaN          NaN
46          NaN          NaN
47          NaN          NaN
48          NaN          NaN